version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: db
    hostname: postgres
    environment:
      - POSTGRES_PASSWORD=dashowl
      - POSTGRES_USER=dashowl
      - POSTGRES_DB=dashowl
    ports:
      - 5000:5432

  web:
    build: .
    command: /bin/sh ./boot.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    environment:
      - DB_NAME=dashowl
      - DB_USER=dashowl
      - DB_PASSWORD=dashowl
      - DB_HOST=postgres
    depends_on:
      - postgres
